### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Djyp** [Oppskrift/oppskrift_doc#4]
It's doesn't break a duck's third leg (😏) but here's a simple logo I created easily on [freelogodesign.org](https://fr.freelogodesign.org/manager/showcase/ad7cbbf5304e440a843636bb81c847b8).

![ad7cbbf5304e440a843636bb81c847b8](https://user-images.githubusercontent.com/498327/113581615-a4572e80-9627-11eb-9739-22c9b55093e1.png)

I just thought we could use some placeholder in the github organization until we want to get rid of it :shrug:
If the issue is accepted I'd crop the image to keep only the graphic part

**Comment by Scttpr** [comment]
Nice ! I'm not super fan of the orange border, don't you prefer without it ? Otherwise it's super nice (love the blue)

**Comment by Djyp** [comment]
[Sure](https://fr.freelogodesign.org/manager/showcase/ad7cbbf5304e440a843636bb81c847b8) !

![logo_200x200](https://user-images.githubusercontent.com/498327/114081513-f0ff6b80-98ac-11eb-9b3c-a473b933eaa2.png)

**Comment by Djyp** [comment]
Je ferme, on aura mieux le moment voulu

**Comment by Djyp** [comment]
A new and more nice logo has been proposed and we're adopting it until further notice :
![logo-full](https://user-images.githubusercontent.com/498327/117533149-7e88c500-afeb-11eb-8ed1-5b5f567d5f83.png)

**Comment by Djyp** [comment]
The logo has been updated to the organization
